### ISSUE TITLE
Make bot play NEEEEEE randomnly lets say 10% of the time someone joins a voice channel?

### ISSUE THREAD

**Issue by Bruhtek** [Bruhtek/HoloBot#24]
For example using [voiceStateUpdate](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-voiceStateUpdate) as a trigger?

**Comment by kaubGit** [comment]
Ye brilliant idea ye pls add this ye

**Comment by Bruhtek** [comment]
Done in #25
